language: python
python:
  - "3.6.2"
cache: pip

services:
  -postgresql

before_script:
  - psql -c 'CREATE DATABASE mydiary;' -U postgres
# install dependencies
install:
  - pip install -r requirements.txt

# run tests
script:
  - pytest --cov=api

after_success:
  - coveralls
