language: python
python:
  - "3.6.2"
cache: pip

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

# run tests
script:
  - pytest --with-coverage --cover-tests --cover-package=api/tests
  - coverage report

after_success:
  - coveralls